source 'https://rubygems.org'

ruby '2.2.0'

gem 'rails', '4.2.0'

gem 'rails-api'

gem 'spring', :group => :development

gem 'dotenv-rails'
gem 'httparty'

gem 'pg'

gem 'bcrypt', '~> 3.1.7'

gem 'rails_12factor', group: :production

group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers'
  gem 'factory_girl_rails'
  gem 'database_cleaner'
  gem 'faker'
end
